SET TIME_ZONE='-05:00';

DROP TABLE IF EXISTS `facility_pool`;
DROP TABLE IF EXISTS `facility_activity`;
DROP TABLE IF EXISTS `available_activity`;
DROP TABLE IF EXISTS `facility_reservation`;
DROP TABLE IF EXISTS `activity`;
DROP TABLE IF EXISTS `type`;
DROP TABLE IF EXISTS `pool`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `facility`;

--
-- Table structure for table `FACILITY`
--

CREATE TABLE `facility` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KEYY` varchar(25) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `URL` varchar(250) NOT NULL,
  `ADDRESS` varchar(250) NOT NULL,
  `PHONE` varchar(12) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `LNG` decimal(12,10) NOT NULL,
  `LAT` decimal(12,10) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `URL` (`URL`),
  UNIQUE KEY `KEYY` (`KEYY`),
  UNIQUE KEY `TITLE` (`TITLE`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `CATEGORY`
--

CREATE TABLE `category` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KEYY` varchar(25) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE` (`TITLE`),
  UNIQUE KEY `KEYY` (`KEYY`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `POOL`
--

CREATE TABLE `pool` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `LENGTH` int NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `INDOOR` tinyint(1) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


--
-- Table structure for table `type`
--

CREATE TABLE `type` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KEYY` varchar(25) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `CATEGORY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE` (`TITLE`),
  UNIQUE KEY `KEYY` (`KEYY`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  CONSTRAINT `TYPE_ibfk_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `category` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `ACTIVITY`
--

CREATE TABLE `activity` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) NOT NULL,
  `TYPE_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE` (`TITLE`),
  KEY `TYPE_ID` (`TYPE_ID`),
  CONSTRAINT `ACTIVITY_ibfk_1` FOREIGN KEY (`TYPE_ID`) REFERENCES `type` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=175 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `FACILITY_RESERVATION`
--

CREATE TABLE `facility_reservation` (
  `ID` varchar(30) NOT NULL,
  `FACILITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_ID` (`FACILITY_ID`),
  CONSTRAINT `FACILITY_RESERVATION_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `facility` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `AVAILABLE_ACTIVITY`
--

CREATE TABLE `available_activity` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TIME` DATETIME NOT NULL,
  `AVAILABLE` tinyint NOT NULL,
  `FACILITY_RESERVATION_ID` varchar(30) NOT NULL,
  `ACTIVITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_RESERVATION_ID` (`FACILITY_RESERVATION_ID`),
  KEY `ACTIVITY_ID` (`ACTIVITY_ID`),
  CONSTRAINT `AVAILABLE_ACTIVITY_ibfk_1` FOREIGN KEY (`FACILITY_RESERVATION_ID`) REFERENCES `facility_reservation` (`ID`),
  CONSTRAINT `AVAILABLE_ACTIVITY_ibfk_2` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `activity` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=530 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `FACILITY_ACTIVITY`
--

CREATE TABLE `facility_activity` (
  `FACILITY_ID` int NOT NULL,
  `ACTIVITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FACILITY_ID`,`ACTIVITY_ID`),
  KEY `ACTIVITY_ID` (`ACTIVITY_ID`),
  CONSTRAINT `FACILITY_ACTIVITY_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `facility` (`ID`),
  CONSTRAINT `FACILITY_ACTIVITY_ibfk_2` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `activity` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


--
-- Table structure for table `FACILITY_POOL`
--

CREATE TABLE `facility_pool` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FACILITY_ID` int NOT NULL,
  `POOL_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_ID` (`FACILITY_ID`),
  KEY `POOL_ID` (`POOL_ID`),
  CONSTRAINT `FACILITY_POOL_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `facility` (`ID`),
  CONSTRAINT `FACILITY_POOL_ibfk_2` FOREIGN KEY (`POOL_ID`) REFERENCES `pool` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;